In [273]:
#Import numpy and Matplotlib modules
import numpy as np
import matplotlib.pyplot as plt
#ignore warning message
import warnings
warnings.filterwarnings('ignore')

# Q1. Create a Python list representing vector v = [2, -1, 3] and multiply it by scalar 4

In [274]:
python_list = [2, -1, 3]
python_list = python_list * 4
print(python_list)

[2, -1, 3, 2, -1, 3, 2, -1, 3, 2, -1, 3]


In linear algebra, the product of a vector is defined as the multiplication of its components

In [275]:
np_list = np.array([2, -1, 3])
print(np_list * 4)

[ 8 -4 12]


# Q2. Given vector a = [5, -3] and scalar $\lambda$ =-2:

In [276]:
a = np.array([5, -3])
lam = -2
a = lam * a
print(a)

[-10   6]


In [277]:
norm_a = np.linalg.norm(a)
norm_lam_a = np.linalg.norm(lam * a)
print(f"Norm a: {norm_a}, Norm lambda * a: {norm_lam_a}")

Norm a: 11.661903789690601, Norm lambda * a: 23.323807579381203


Multiplying by $\lambda $ doubled the length of the vector and changed its direction because it is negative

# Q3. Create Column vector shape (3,1) Row vector shape (1,4)

In [278]:
col_v = np.array([[1, 2, 3]]).T

In [279]:
row_v = np.array([[1, 2, 3, 4]])

In [280]:
print(col_v.shape)
print(row_v.shape)

(3, 1)
(1, 4)


In [281]:
col_v + row_v

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

# Q4 . Create vector v = [1,2,3,4] and add scalar 5. Explain why NumPy allows this.

In [282]:
v = np.array([1, 2, 3, 4])
print(v + 5)

[6 7 8 9]


NumPy uses broadcasting. It convert the scalar 5 into a vector of the same dimension [5, 5, 5, 5] to perform element-wise addition.

# Q5. Given vector a = [1,2,3,4,5,6], compute its Euclidean norm manually and using NumPy

In [283]:
a = np.array([1, 2, 3, 4, 5, 6])

In [284]:
np.sqrt(np.sum(a ** 2))

np.float64(9.539392014169456)

In [285]:
np.linalg.norm(a)

np.float64(9.539392014169456)

# Q6. Generate a random vector of length 10 and normalize it. Print the norm before and after normalization

In [286]:
v = np.random.randn(10)
v = v * 10 / np.linalg.norm(v)
v

array([-0.7207459 ,  3.37461044,  2.48403705, -1.22173479, -2.2958342 ,
        5.11548666, -0.76894582,  0.1049189 ,  3.48067087, -6.02271035])

In [287]:
n_v = v / np.linalg.norm(v)

In [288]:
print(f'Before: {np.linalg.norm(v)}')
print(f'After: {np.linalg.norm(n_v)}')

Before: 10.0
After: 0.9999999999999999


# Q7. Compute the dot product of vectors

In [289]:
a = [1, 2, 3, 4, 5, 6] 
b = [0, -4, 3, -3, 6, 5]

In [290]:
res = 0
for i in range(len(a)):
    res += a[i] * b[i]
res

49

In [291]:
np.dot(a, b)

np.int64(49)

# Q8. Verify the distributive property:

In [292]:
a = np.random.randn(10)
b = np.random.randn(10)
c = np.random.randn(10)

In [293]:
r1 = np.dot(a, b) + np.dot(a, c)
r2 = np.dot(a, (b+c))

print(f'R1 = {r1}')
print(f'R2 = {r2}')

R1 = -1.2589952069567938
R2 = -1.2589952069567938


# Q9: Compute the Euclidean distance matrix between every point in group A and every point in group B.

In [294]:
A = np.array([
 [ 2, 1],
 [ 5, 4],
 [ 1, 6],
 [ 7, 2]
])

In [295]:
B = np.array([
 [0, 0],
 [6, 3],
 [3, 5]
])

In [296]:
A_n = A[:, np.newaxis, :]
B_n = B[np.newaxis, :, :]

In [297]:
diff = A_n - B_n
sq_diff = diff ** 2

In [298]:
sum_sq = np.sum(sq_diff, axis=2)
dist_matrix = np.sqrt(sum_sq)

In [299]:
print(dist_matrix)

[[2.23606798 4.47213595 4.12310563]
 [6.40312424 1.41421356 2.23606798]
 [6.08276253 5.83095189 2.23606798]
 [7.28010989 1.41421356 5.        ]]
